{
 "title": "app",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "JOB", "query": "webservice" }
  ]
 },
 "panels": [
  {
   "title": "Active Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "webstore_active_upload_requests",
     "legendFormat": "active uploads"
    },
    {
     "expr": "webstore_active_download_requests",
     "legendFormat": "active downloads"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(webstore_upload_duration_count{instance=\"localhost:8080\"}[10s])",
     "legendFormat": "upload"
    },
    {
     "expr": "rate(webstore_download_duration_count{instance=\"localhost:8080\"}[10s])",
     "legendFormat": "download"
    }
   ]
  },
  {
   "title": "Upload Service Time Breakdown",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "webstore_upload_duration{quantile=\"0.99\"}",
     "legendFormat": "end-to-end"
    },
    {
     "expr": "webstore_encryption_duration{quantile=\"0.99\"}",
     "legendFormat": "encryption"
    },
    {
     "expr": "webstore_write_duration{quantile=\"0.99\"}",
     "legendFormat": "write to file"
    }
   ]
  },
  {
   "title": "Download Service Time Breakdown",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "webstore_download_duration{quantile=\"0.99\"}",
     "legendFormat": "end-to-end"
    },
    {
     "expr": "webstore_decryption_duration{quantile=\"0.99\"}",
     "legendFormat": "decryption"
    },
    {
     "expr": "webstore_read_duration{quantile=\"0.99\"}",
     "legendFormat": "read from file"
    }
   ]
  },
  {
   "title": "Application CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"localhost:8080\"}[10s]) / 4",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Application Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"$JOB\"}",
     "legendFormat": "allocated"
    },
    {
     "expr": "go_memstats_next_gc_bytes{job=\"$JOB\"}",
     "legendFormat": "to be garbage-collected"
    }
   ]
  },
  {
   "title": "Go Routines & Threads",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{instance=\"localhost:8080\"}",
     "legendFormat": "Go routines"
    },
    {
     "expr": "go_threads{instance=\"localhost:8080\"}",
     "legendFormat": "Go threads"
    }
   ]
  }
 ]
}