{
 "title": "webstore",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Active Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "webstore_active_upload_requests",
     "legendFormat": "Active Uploads"
    },
    {
     "expr": "webstore_active_download_requests",
     "legendFormat": "Active Downloads"
    }
   ]
  },
  {
   "title": "Requests per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(webstore_upload_duration_count{instance=\"localhost:8080\"}[10s])",
     "legendFormat": "Upload RPS"
    },
    {
     "expr": "rate(webstore_download_duration_count{instance=\"localhost:8080\"}[10s])",
     "legendFormat": "Download RPS"
    }
   ]
  },
  {
   "title": "Upload Service Time (seconds)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "webstore_upload_duration", "legendFormat": "P{{quantile}}" }
   ]
  },
  {
   "title": "Download Service Time (seconds)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "webstore_download_duration", "legendFormat": "P{{quantile}}" }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"localhost:8080\"}[10s]) / 4"
    }
   ]
  },
  {
   "title": "Go Memory Usage vs to be Garbage-Collected (Megabytes)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes / 1024 / 1024",
     "legendFormat": "Allocated Megabytes"
    },
    {
     "expr": "go_memstats_next_gc_bytes / 1024 / 1024",
     "legendFormat": "Next Garbage Collection Megabytes"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{instance=\"localhost:8080\"}",
     "legendFormat": "Go routines"
    }
   ]
  }
 ]
}