{
 "title": "system",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "JOB", "query": "node" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1.0 - sum(rate(node_cpu_seconds_total{mode=\"idle\",job=\"$JOB\"}[10s])) / 4",
     "legendFormat": "total"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"system\",job=\"$JOB\"}[10s])) / 4",
     "legendFormat": "system"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"user\",job=\"$JOB\"}[10s])) / 4",
     "legendFormat": "user"
    },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode=\"iowait\",job=\"$JOB\"}[10s])) / 4",
     "legendFormat": "iowait"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "total" },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemFree_bytes",
     "legendFormat": "used"
    },
    { "expr": "node_memory_Cached_bytes", "legendFormat": "cached" },
    { "expr": "node_memory_Buffers_bytes", "legendFormat": "buffered" }
   ]
  },
  {
   "title": "Disk I/O Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{device=\"sda\"}[10s])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{device=\"sda\"}[10s])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "node_memory_SwapTotal_bytes", "legendFormat": "total" },
    {
     "expr": "(node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes)/ 1024 / 1024",
     "legendFormat": "used"
    },
    { "expr": "node_memory_SwapCached_bytes", "legendFormat": "cached" }
   ]
  },
  {
   "title": "Disk I/O Bytes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"sda\"}[10s])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"sda\"}[10s])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Disk I/O Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{device=\"sda\"}[10s])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{device=\"sda\"}[10s])",
     "legendFormat": "write"
    }
   ]
  }
 ]
}